[package]
name = "pl0"
version = "0.1.0"
authors = ["Matt Godshall <lifeinhex@gmail.com>, chyyuu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
